# Generated by Django 6.0.2 on 2026-02-22 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punishments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punishmenttake',
            name='target',
        ),
        migrations.AlterField(
            model_name='punishmentevent',
            name='amount',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='punishmentevent',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='punishmentevent',
            constraint=models.CheckConstraint(condition=models.Q(('initiator', models.F('target')), _negated=True), name='pe_initiator_not_target'),
        ),
        migrations.AddConstraint(
            model_name='punishmentevent',
            constraint=models.CheckConstraint(condition=models.Q(('confirmer__isnull', True), models.Q(('confirmer', models.F('initiator')), _negated=True), _connector='OR'), name='pe_confirmer_not_initiator'),
        ),
        migrations.AddConstraint(
            model_name='punishmentevent',
            constraint=models.CheckConstraint(condition=models.Q(('confirmer__isnull', True), models.Q(('confirmer', models.F('target')), _negated=True), _connector='OR'), name='pe_confirmer_not_target'),
        ),
        migrations.DeleteModel(
            name='PunishmentTake',
        ),
    ]
