# Generated by Django 6.0.2 on 2026-02-26 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punishments', '0003_takepunishmentevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FikapinneEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fikapinnar_given', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fikapinnar_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('manage_fikapinnar', 'Can give/take fikapinnar')],
                'constraints': [models.CheckConstraint(condition=models.Q(('judge', models.F('target')), _negated=True), name='fe_judge_not_target')],
            },
        ),
        migrations.CreateModel(
            name='TakeFikapinneEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fikapinnar_taken_by', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fikapinnar_taken_from', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('judge', models.F('target')), _negated=True), name='tfe_judge_not_target')],
            },
        ),
    ]
