# Generated by Django 6.0.3 on 2026-03-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punishments', '0005_reason_max_length'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE punishments_punishmentevent SET reason = LEFT(reason, 100) WHERE LENGTH(reason) > 100;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='punishmentevent',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
