# Generated by Django 6.0.3 on 2026-03-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punishments', '0006_reason_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punishmentevent',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
