# Generated by Django 6.0.2 on 2026-02-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='force_password_reset',
            field=models.BooleanField(default=True),
        ),
    ]
