# Generated by Django 6.0.2 on 2026-02-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_force_password_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.CharField(choices=[('bandana', 'Bandana'), ('hat', 'Hat'), ('vest', 'Vest')], default='vest', max_length=20),
        ),
    ]
